//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eli_mubu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fhnEntities3 : DbContext
    {
        public fhnEntities3()
            : base("name=fhnEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Benefits> Benefits { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Footer> Footer { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<IconFeature> IconFeature { get; set; }
        public virtual DbSet<Icons> Icons { get; set; }
        public virtual DbSet<Screenshots> Screenshots { get; set; }
        public virtual DbSet<sPhoto> sPhoto { get; set; }
        public virtual DbSet<Statisticas> Statisticas { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<Buyns> Buyns { get; set; }
        public virtual DbSet<Buys> Buys { get; set; }
        public virtual DbSet<Teamas> Teamas { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
    }
}
