//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eli_mubu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Text { get; set; }
        public string Photo { get; set; }
        public string Icon { get; set; }
        public string IconHead { get; set; }
        public string IconTxt { get; set; }
    }
}
