//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eli_mubu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fhnEntities : DbContext
    {
        public fhnEntities()
            : base("name=fhnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Benefit> Benefits { get; set; }
        public virtual DbSet<Buyn> Buyns { get; set; }
        public virtual DbSet<Buy> Buys { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<IconFeature> IconFeatures { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<Screenshot> Screenshots { get; set; }
        public virtual DbSet<sPhoto> sPhotoes { get; set; }
        public virtual DbSet<Statistica> Statisticas { get; set; }
        public virtual DbSet<Teama> Teamas { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
